#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define RENDER_SCALE 3
#define DISPLAY_WIDTH (float) SCREEN_WIDTH / RENDER_SCALE 
#define DISPLAY_HEIGHT (float) SCREEN_HEIGHT / RENDER_SCALE 
#define MAX_ENTITY_COUNT 255

#define REFRESH_RATE 165

#define TIME_STEP 0.01f
