#pragma once

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600
#define RENDER_SCALE 3
#define DISPLAY_WIDTH SCREEN_WIDTH / RENDER_SCALE 
#define DISPLAY_HEIGHT SCREEN_HEIGHT / RENDER_SCALE 
#define MAX_ENTITY_COUNT 255
